#this approach developed with Josh from Zapi at Ruby hacknight

default: &default
 grades:
  - 6a
  - 6a+
  - 6b
  - 6b+
  - 6c
  - 6c+
  - 7a
  - 7a+
  - 7b
  - 7b+
  - 7c
  - 7c+
  - 8a
  - 8a+
  - 8b
  - 8b+
  - 8c
  - 8c+
  - proj

 ratings:
  - 0
  - 1
  - 2
  - 3

 holds:
  - top
  - last move
  - 2nd last move
  - midway
  - done 2nd move
  - done 1st move
  - working 1st move
  - don't care
  - Woods
  - Ondra
  - Puccio
  - Megos
  - Graham
  - Robinson
  - Coxsey
  - Midtbo
  - Sharma
  - Hill
  - Hukkataival
  - McClure
  - Gullich
  - TL1
  - TL2
  - TL3
  - TL4
  - TLC
  - TR1
  - TR2
  - TR3
  - TR4
  - TRC
  - DL1
  - DL2
  - DL3
  - DL4
  - DL5
  - DL6
  - DL7
  - DL8
  - DL9
  - DL10
  - DL11
  - DL12
  - DL13
  - DL14
  - DL15
  - DL16
  - DL17
  - DL18
  - DL19
  - DL20
  - DL21
  - DL22
  - DL23
  - DL24
  - DL25
  - DL26
  - DL27
  - DL28
  - DL29
  - DL30
  - DL31
  - DL32
  - DL33
  - DL34
  - DL35
  - DL36
  - DL37
  - DL38
  - DL39
  - DL40
  - DL41
  - DL42
  - DL43
  - DR1
  - DR2
  - DR3
  - DR4
  - DR5
  - DR6
  - DR7
  - DR8
  - DR9
  - DR10
  - DR11
  - DR12
  - DR13
  - DR14
  - DR15
  - DR16
  - DR17
  - DR18
  - DR19
  - DR20
  - DR21
  - DR22
  - DR23
  - DR24
  - DR25
  - DR26
  - DR27
  - DR28
  - DR29
  - DR30
  - DR31
  - DR32
  - DR33
  - DR34
  - DR35
  - DR36
  - DR37
  - DR38
  - DR39
  - DR40
  - DR41
  - DR42
  - DR43
  - CL1
  - CL2
  - CL3
  - CL4
  - CL5
  - CL6
  - CL7
  - CL8
  - CL9
  - CL10
  - CL11
  - CL12
  - CL13
  - CL14
  - CL15
  - CL16
  - CL17
  - CL18
  - CL19
  - CL20
  - CL21
  - CL22
  - CL23
  - CL24
  - CL25
  - CL26
  - CL27
  - CL28
  - CL29
  - CL30
  - CL31
  - CL32
  - CL33
  - CL34
  - CL35
  - CL36
  - CL37
  - CL38
  - CL39
  - CL40
  - CL41
  - CL42
  - CL43
  - CL44
  - CL45
  - CL46
  - CL47
  - CL48
  - CL49
  - CL50
  - CL51
  - CL52
  - CR1
  - CR2
  - CR3
  - CR4
  - CR5
  - CR6
  - CR7
  - CR8
  - CR9
  - CR10
  - CR11
  - CR12
  - CR13
  - CR14
  - CR15
  - CR16
  - CR17
  - CR18
  - CR19
  - CR20
  - CR21
  - CR22
  - CR23
  - CR24
  - CR25
  - CR26
  - CR27
  - CR28
  - CR29
  - CR30
  - CR31
  - CR32
  - CR33
  - CR34
  - CR35
  - CR36
  - CR37
  - CR38
  - CR39
  - CR40
  - CR41
  - CR42
  - CR43
  - CR44
  - CR45
  - CR46
  - CR47
  - CR48
  - CR49
  - CR50
  - CR51
  - CR52
  - BL1
  - BL2
  - BL3
  - BL4
  - BL5
  - BL6
  - BL7
  - BL8
  - BL9
  - BL10
  - BL11
  - BL12
  - BL13
  - BL14
  - BL15
  - BL16
  - BL17
  - BL18
  - BL19
  - BL20
  - BL21
  - BL22
  - BL23
  - BL24
  - BL25
  - BL26
  - BL27
  - BL28
  - BL29
  - BL30
  - BL31
  - BL32
  - BL33
  - BL34
  - BL35
  - BL36
  - BL37
  - BL38
  - BL39
  - BL40
  - BL41
  - BL42
  - BL43
  - BL44
  - BR1
  - BR2
  - BR3
  - BR4
  - BR5
  - BR6
  - BR7
  - BR8
  - BR9
  - BR10
  - BR11
  - BR12
  - BR13
  - BR14
  - BR15
  - BR16
  - BR17
  - BR18
  - BR19
  - BR20
  - BR21
  - BR22
  - BR23
  - BR24
  - BR25
  - BR26
  - BR27
  - BR28
  - BR29
  - BR30
  - BR31
  - BR32
  - BR33
  - BR34
  - BR35
  - BR36
  - BR37
  - BR38
  - BR39
  - BR40
  - BR41
  - BR42
  - BR43
  - BR44
  - AL1
  - AL2
  - AL3
  - AL4
  - AL5
  - AL6
  - AL7
  - AL8
  - AL9
  - AL10
  - AL11
  - AL12
  - AL13
  - AL14
  - AL15
  - AL16
  - AL17
  - AL18
  - AL19
  - AL20
  - AL21
  - AL22
  - AL23
  - AL24
  - AL25
  - AL26
  - AL27
  - AL28
  - AL29
  - AL30
  - AL31
  - AL32
  - AL33
  - AL34
  - AL35
  - AL36
  - AL37
  - AL38
  - AL39
  - AL40
  - AL41
  - AL42
  - AL43
  - AL44
  - AL45
  - AL46
  - AL47
  - AL48
  - AR1
  - AR2
  - AR3
  - AR4
  - AR5
  - AR6
  - AR7
  - AR8
  - AR9
  - AR10
  - AR11
  - AR12
  - AR13
  - AR14
  - AR15
  - AR16
  - AR17
  - AR18
  - AR19
  - AR20
  - AR21
  - AR22
  - AR23
  - AR24
  - AR25
  - AR26
  - AR27
  - AR28
  - AR29
  - AR30
  - AR31
  - AR32
  - AR33
  - AR34
  - AR35
  - AR36
  - AR37
  - AR38
  - AR39
  - AR40
  - AR41
  - AR42
  - AR43
  - AR44
  - AR45
  - AR46
  - AR47
  - AR48

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
