# default: &default
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   host: localhost
#   username: postgres
#   password: password

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: whack_development

test:
  <<: *default
  database: whack_test

production:
  <<: *default
  database: whack_production
  username: railsapps
  password: <%= Rails.application.credentials.dig(:production, :database_password) %>